import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const firaSans = Fira_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--firaSans",
});

const firaSansItalic = Fira_Sans({
  subsets: ["latin"],
  weight: "400",
  style: "italic",
  variable: "--firaSansItalic",
});

const firaSansBold = Fira_Sans({
  subsets: ["latin"],
  weight: "600",
  variable: "--firaSansBold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.className} ${firaSansItalic.variable} ${firaSansBold.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
